### ISSUE TITLE
Previewing .wav audio files

### ISSUE THREAD

**Issue by jggautier** [QualitativeDataRepository/dataverse-previewers#36]
Would it be possible to add the ability to preview .wave audio files?

**Comment by qqmyers** [comment]
@jggautier  - give it a shot! In theory, as long as the audio tag in html5 plays it, you can just add an external tool manifest specifying the right mimetype. From https://hpr.dogphilosophy.net/test/ it looks like .wav is supported, so if you can find the mimetype being assigned to your file in Dataverse, you should be able to add an external tool entry. 

If that works, we can consider adding it to the default list to install (in the GitHub readme file) - as long as it looks like it works across browsers, there's not much downside to listing it. (That said, we just removed an image format because it was only supported on some browsers.)

If there are issues with the audio tag playing the file, it's a bigger issue - we'd have to find a wav player somewhere to integrate. At first glance, it doesn't look like this is the case though.

**Comment by jggautier** [comment]
Thanks! I'm going to close this issue. If/when we're able to test playing .wave files in different browsers and it works well, we'll open an issue about adding it to that default list in the readme.
